apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: personal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: inventory
            - name: MYSQL_USER
              value: ecommerce
            - name: MYSQL_PASSWORD
              value: ecommerce
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-uecommerce", "-pecommerce"]
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: personal
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
