namespace: personal

eureka:
  url: http://service-discovery.personal.svc.cluster.local:8761/eureka/

env:
  - name: SPRING_PROFILES_ACTIVE
    value: kubernetes
  - name: SPRING_MONGODB_URI
    value: mongodb://mongodb:27017/notification_db
  - name: APP_KAFKA_ENABLED
    value: "false"

probes:
  readiness:
    initialDelaySeconds: 60
    periodSeconds: 15
  liveness:
    initialDelaySeconds: 90
    periodSeconds: 20
